version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: fastapi_app_prod
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      target: production  # Use production stage
    container_name: react_app_prod
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: postgres_db_prod
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: